name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Get version
      id: version
      run: |
        echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - uses: snok/install-poetry@v1.1.3
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - uses: actions/cache@v2
      id: cached-dependecies
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ matrix.python-version }}-no-dev

    - name: Validate pyproject.toml
      run: poetry check

    - name: Install dependencies
      if: steps.cached-dependecies.outputs.cache-hit != 'true'
      run: poetry install --no-dev

    - name: Publish to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: poetry publish --build -n

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: v${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
        files: |
          dist/donphan-${{ steps.version.outputs.version }}.tar.gz
          dist/donphan-${{ steps.version.outputs.version }}-py3-none-any.whl
